# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EKMapServerPublisher
                                 A QGIS plugin
 Publisher plugin for eKMap Server
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-08-28
        copyright            : (C) 2020 by eKGIS
        email                : info@ekgis.com.vn
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EKMapServerPublisher class from file EKMapServerPublisher.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ekmap_server_publisher import EKMapServerPublisher
    return EKMapServerPublisher(iface)
